# Generated by Django 5.2.3 on 2025-07-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.kelompok')),
            ],
        ),
        migrations.CreateModel(
            name='Objek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.jenis')),
            ],
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.provinsi')),
            ],
        ),
        migrations.CreateModel(
            name='RincianObjek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('objek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.objek')),
            ],
        ),
        migrations.CreateModel(
            name='SubRincianObjek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('rincian_objek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.rincianobjek')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubRincianObjek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('sub_rincian_objek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.subrincianobjek')),
            ],
        ),
        migrations.CreateModel(
            name='RincianBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255, unique=True)),
                ('kode_lengkap', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('sub_sub_rincian_objek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.subsubrincianobjek')),
            ],
        ),
        migrations.CreateModel(
            name='UnitBidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=255, unique=True, verbose_name='Nama Unit Bidang')),
                ('nama_kepala_dinas', models.CharField(max_length=255)),
                ('nip_kepala_dinas', models.CharField(max_length=50)),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.kota')),
            ],
        ),
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bidang', models.CharField(max_length=100, verbose_name='Nama Bidang/Seksi')),
                ('unit_bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.unitbidang')),
            ],
        ),
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=260, verbose_name='Nama/Merek/Tipe Barang')),
                ('nomor_register', models.CharField(blank=True, max_length=50, null=True)),
                ('ukuran', models.CharField(blank=True, max_length=50, null=True)),
                ('bahan', models.CharField(blank=True, max_length=100, null=True)),
                ('nomor_pabrik', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor Pabrik/Chasis')),
                ('nomor_rangka', models.CharField(blank=True, max_length=100, null=True)),
                ('nomor_mesin', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_pembelian', models.DateField()),
                ('harga_pembelian', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Baik', 'Baik'), ('Perbaikan', 'Perbaikan'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang')], default='Baik', max_length=20)),
                ('kode_aset', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('terakhir_diperbarui', models.DateTimeField(auto_now=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('didaftarkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aset.bidang')),
                ('klasifikasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aset.subsubrincianobjek', verbose_name='Klasifikasi Barang')),
                ('unit_bidang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aset.unitbidang')),
            ],
            options={
                'verbose_name_plural': 'Daftar Aset',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
