# Generated by Django 5.2.3 on 2025-07-04 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RincianBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255, unique=True)),
                ('kode_lengkap', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.kelompok')),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lokasi', models.CharField(max_length=100)),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.kota')),
            ],
        ),
        migrations.CreateModel(
            name='Objek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.jenis')),
            ],
        ),
        migrations.AddField(
            model_name='kota',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.provinsi'),
        ),
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembelian', models.DateField()),
                ('harga_pembelian', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Baik', 'Baik'), ('Perbaikan', 'Perbaikan'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang')], default='Baik', max_length=20)),
                ('kode_aset', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('terakhir_diperbarui', models.DateTimeField(auto_now=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('didaftarkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aset.lokasi')),
                ('rincian_barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aset.rincianbarang', verbose_name='Nama & Jenis Barang')),
            ],
            options={
                'verbose_name_plural': 'Daftar Aset',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='RincianObjek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('objek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.objek')),
            ],
        ),
        migrations.CreateModel(
            name='SubRincianObjek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('rincian_objek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.rincianobjek')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubRincianObjek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('sub_rincian_objek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.subrincianobjek')),
            ],
        ),
        migrations.AddField(
            model_name='rincianbarang',
            name='sub_sub_rincian_objek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.subsubrincianobjek'),
        ),
    ]
