# Generated by Django 5.2.3 on 2025-07-28 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pekerjaan', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='aset',
            name='jenis_belanja',
            field=models.CharField(choices=[('LS', 'LS - Langsung'), ('GU', 'GU - Ganti Uang')], default='LS', max_length=2),
        ),
        migrations.AlterField(
            model_name='aset',
            name='nomor_register',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=255)),
                ('pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.pekerjaan')),
            ],
        ),
        migrations.CreateModel(
            name='SubKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sub_kegiatan', models.CharField(max_length=255)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.kegiatan')),
            ],
        ),
        migrations.AddField(
            model_name='aset',
            name='sub_kegiatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aset.subkegiatan'),
        ),
    ]
