# Generated by Django 5.2.3 on 2025-07-09 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aset',
            options={},
        ),
        migrations.AddField(
            model_name='aset',
            name='klasifikasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aset.subsubrincianobjek', verbose_name='Klasifikasi Barang'),
        ),
        migrations.AddField(
            model_name='aset',
            name='nama_barang',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Nama/Merek/Tipe Barang'),
        ),
    ]
