# Generated by Django 5.2.3 on 2025-07-29 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0002_pekerjaan_aset_jenis_belanja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruangan', models.CharField(max_length=100, verbose_name='Nama Ruangan Pakai')),
                ('kode_lokasi', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_kepala_ruangan', models.CharField(blank=True, max_length=255, null=True)),
                ('nip_kepala_ruangan', models.CharField(blank=True, max_length=50, null=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.bidang')),
            ],
        ),
        migrations.AddField(
            model_name='aset',
            name='ruangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aset.ruangan'),
        ),
    ]
