# Generated by Django 5.2.3 on 2025-07-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0002_alter_aset_options_aset_klasifikasi_aset_nama_barang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aset',
            options={'ordering': ['-dibuat_pada'], 'verbose_name_plural': 'Daftar Aset'},
        ),
        migrations.RemoveField(
            model_name='aset',
            name='rincian_barang',
        ),
        migrations.AddField(
            model_name='aset',
            name='bahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aset',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aset',
            name='nomor_mesin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aset',
            name='nomor_pabrik',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor Pabrik/Chasis'),
        ),
        migrations.AddField(
            model_name='aset',
            name='nomor_rangka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aset',
            name='nomor_register',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aset',
            name='ukuran',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='klasifikasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aset.subsubrincianobjek', verbose_name='Klasifikasi Barang'),
        ),
        migrations.AlterField(
            model_name='aset',
            name='nama_barang',
            field=models.CharField(max_length=255, verbose_name='Nama/Merek/Tipe Barang'),
        ),
    ]
