# Generated by Django 5.2.3 on 2025-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0003_ruangan_aset_ruangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruangan',
            name='nama_kepala_ruangan',
        ),
        migrations.RemoveField(
            model_name='ruangan',
            name='nip_kepala_ruangan',
        ),
        migrations.AddField(
            model_name='bidang',
            name='nama_kepala_bidang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bidang',
            name='nip_kepala_bidang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
