# Generated by Django 5.2.3 on 2025-07-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0003_alter_aset_options_remove_aset_rincian_barang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aset',
            name='nama_barang',
            field=models.CharField(max_length=260, verbose_name='Nama/Merek/Tipe Barang'),
        ),
    ]
