# Generated by Django 5.2.3 on 2025-07-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0004_alter_aset_nama_barang'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitBidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=255, unique=True)),
                ('nama_kepala_dinas', models.CharField(max_length=255)),
                ('nip_kepala_dinas', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='aset',
            name='unit_bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aset.unitbidang'),
        ),
    ]
