# Generated by Django 5.2.3 on 2025-07-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0004_remove_ruangan_nama_kepala_ruangan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aset',
            name='nama_barang',
        ),
        migrations.AddField(
            model_name='aset',
            name='merek_tipe',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='Merek/Tipe'),
        ),
        migrations.AlterField(
            model_name='bidang',
            name='nama_bidang',
            field=models.CharField(max_length=100, verbose_name='Nama Bidang'),
        ),
        migrations.AlterField(
            model_name='bidang',
            name='nama_kepala_bidang',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Kepala Bidang'),
        ),
        migrations.AlterField(
            model_name='bidang',
            name='nip_kepala_bidang',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP Kepala Bidang'),
        ),
        migrations.AlterField(
            model_name='bidang',
            name='unit_bidang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aset.unitbidang', verbose_name='Nama OPD'),
        ),
        migrations.AlterField(
            model_name='unitbidang',
            name='nama_kepala_dinas',
            field=models.CharField(max_length=255, verbose_name='Nama Kepala Dinas'),
        ),
        migrations.AlterField(
            model_name='unitbidang',
            name='nip_kepala_dinas',
            field=models.CharField(max_length=50, verbose_name='NIP Kepala Dinas'),
        ),
    ]
