# Generated by Django 5.2.3 on 2025-08-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0005_remove_aset_nama_barang_aset_merek_tipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusKepemilikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=2, unique=True)),
                ('uraian', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusKompabilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=1, unique=True)),
                ('uraian', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bidang',
            name='kode',
            field=models.CharField(default='00', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruangan',
            name='kode',
            field=models.CharField(default='00', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitbidang',
            name='kode',
            field=models.CharField(default='00', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aset',
            name='status_kepemilikan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aset.statuskepemilikan'),
        ),
        migrations.AddField(
            model_name='aset',
            name='status_kompabilitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aset.statuskompabilitas'),
        ),
    ]
