# Generated by Django 5.2.3 on 2025-08-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0006_statuskepemilikan_statuskompabilitas_bidang_kode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aset',
            name='bahan',
        ),
        migrations.RemoveField(
            model_name='aset',
            name='nomor_pabrik',
        ),
        migrations.RemoveField(
            model_name='aset',
            name='status_kepemilikan',
        ),
        migrations.RemoveField(
            model_name='aset',
            name='status_kompabilitas',
        ),
        migrations.RemoveField(
            model_name='aset',
            name='ukuran',
        ),
        migrations.AddField(
            model_name='aset',
            name='akumulasi_penyusutan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='aset',
            name='cara_perolehan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aset',
            name='nilai_rehab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='aset',
            name='nomor_bpkb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor BPKB'),
        ),
        migrations.AddField(
            model_name='aset',
            name='nomor_induk_barang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aset',
            name='nomor_polisi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aset',
            name='penyusutan_semester',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Penyusutan Semester Ini'),
        ),
        migrations.AddField(
            model_name='aset',
            name='spesifikasi_lokasi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spesifikasi Lokasi Lainnya'),
        ),
        migrations.AddField(
            model_name='aset',
            name='status_penggunaan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aset',
            name='harga_pembelian',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Perolehan'),
        ),
    ]
