# Generated by Django 5.2.3 on 2025-08-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset', '0007_remove_aset_bahan_remove_aset_nomor_pabrik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aset',
            name='status_kepemilikan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aset.statuskepemilikan'),
        ),
        migrations.AddField(
            model_name='aset',
            name='status_kompabilitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aset.statuskompabilitas'),
        ),
    ]
